name: "PR Checks"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv

    - name: devenv test
      run: devenv test

    # on a local machine this is already in place
    # but on a fresh github actions worker it won't be
    - name: generate .env-phoenix-test
      shell: devenv shell bash -- -e {0}
      run: bash -x .github/workflows/generate-env-phoenix-test.sh

    - name: ci steps
      shell: devenv shell bash -- -e {0}
      run: |
        devenv up -d
        bash -x .github/workflow/pr-request-actions.sh
